### ISSUE TITLE
`Try in browser` link is down

### ISSUE THREAD

**Issue by joepio** [notation-fun/notation#164]
Looks like a really cool project!

On https://www.notation.fun/ there's a `try in browser` link that points to
https://www.amateurguitar.com/songs/scarborough-fair/

Unfortunately, this results in a 404.

**Comment by yjpark** [comment]
Hi Joep,

Thanks for checking in the fun notation project, and for finding the 404
link, fixed and updated (changed the way to host tab file, forgot to update
the link).

Best Regards,

Park
